#!/usr/bin/env python3

import os
import time
import subprocess
import argparse

parser = argparse.ArgumentParser(
        description="A version of strace using eBPF and tracepoints.")

parser.add_argument('cmd', help="The command to trace (in quotes).")
args = parser.parse_args()

"""
We don't want to wait within the parent--we want the child
and the parent to run (almost) simulataneously, so that we
can start tracing within the parent immediately.
"""
def main():
    newpid = os.fork()
   
    if (newpid == 0):
        # Give the parent some time to allow it to start tracing
        # before we run the child.
        time.sleep(2)
        # Execute our command.
        subprocess.run(args.cmd.split())
    else:
        # We are within the parent (Parent PID, child PID)
        pids = (os.getpid(), newpid)
        print(f"Parent PID: {pids[0]}, Child PID: {pids[1]}")
        subprocess.run(["./tracepoint-raw", "-p", str(newpid)])

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("End tracing...")
        exit()


